// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Group) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Permission) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Policy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyBindings) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyBindingsV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyBoundary) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServiceUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}
