// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PolicyBoundaryInitParameters struct {

	// (String) The name of the policy
	// The name of the policy
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The boundary query
	// The boundary query
	Query *string `json:"query,omitempty" tf:"query,omitempty"`
}

type PolicyBoundaryObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the policy
	// The name of the policy
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The boundary query
	// The boundary query
	Query *string `json:"query,omitempty" tf:"query,omitempty"`
}

type PolicyBoundaryParameters struct {

	// (String) The name of the policy
	// The name of the policy
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The boundary query
	// The boundary query
	// +kubebuilder:validation:Optional
	Query *string `json:"query,omitempty" tf:"query,omitempty"`
}

// PolicyBoundarySpec defines the desired state of PolicyBoundary
type PolicyBoundarySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PolicyBoundaryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyBoundaryInitParameters `json:"initProvider,omitempty"`
}

// PolicyBoundaryStatus defines the observed state of PolicyBoundary.
type PolicyBoundaryStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PolicyBoundaryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PolicyBoundary is the Schema for the PolicyBoundarys API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,dynatrace}
type PolicyBoundary struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.query) || (has(self.initProvider) && has(self.initProvider.query))",message="spec.forProvider.query is a required parameter"
	Spec   PolicyBoundarySpec   `json:"spec"`
	Status PolicyBoundaryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyBoundaryList contains a list of PolicyBoundarys
type PolicyBoundaryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyBoundary `json:"items"`
}

// Repository type metadata.
var (
	PolicyBoundary_Kind             = "PolicyBoundary"
	PolicyBoundary_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyBoundary_Kind}.String()
	PolicyBoundary_KindAPIVersion   = PolicyBoundary_Kind + "." + CRDGroupVersion.String()
	PolicyBoundary_GroupVersionKind = CRDGroupVersion.WithKind(PolicyBoundary_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyBoundary{}, &PolicyBoundaryList{})
}
