// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this PolicyBindingsV2.
func (mg *PolicyBindingsV2) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Group),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.GroupRef,
		Selector:     mg.Spec.ForProvider.GroupSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Group")
	}
	mg.Spec.ForProvider.Group = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.GroupRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Policy); i3++ {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Policy[i3].Boundaries),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.ForProvider.Policy[i3].BoundariesRefs,
			Selector:      mg.Spec.ForProvider.Policy[i3].BoundariesSelector,
			To: reference.To{
				List:    &PolicyBoundaryList{},
				Managed: &PolicyBoundary{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Policy[i3].Boundaries")
		}
		mg.Spec.ForProvider.Policy[i3].Boundaries = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.ForProvider.Policy[i3].BoundariesRefs = mrsp.ResolvedReferences

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.Policy); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Policy[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Policy[i3].IDRef,
			Selector:     mg.Spec.ForProvider.Policy[i3].IDSelector,
			To: reference.To{
				List:    &PolicyList{},
				Managed: &Policy{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Policy[i3].ID")
		}
		mg.Spec.ForProvider.Policy[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Policy[i3].IDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Group),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.GroupRef,
		Selector:     mg.Spec.InitProvider.GroupSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Group")
	}
	mg.Spec.InitProvider.Group = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.GroupRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.Policy); i3++ {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.Policy[i3].Boundaries),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.InitProvider.Policy[i3].BoundariesRefs,
			Selector:      mg.Spec.InitProvider.Policy[i3].BoundariesSelector,
			To: reference.To{
				List:    &PolicyBoundaryList{},
				Managed: &PolicyBoundary{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Policy[i3].Boundaries")
		}
		mg.Spec.InitProvider.Policy[i3].Boundaries = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.InitProvider.Policy[i3].BoundariesRefs = mrsp.ResolvedReferences

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Policy); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Policy[i3].ID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Policy[i3].IDRef,
			Selector:     mg.Spec.InitProvider.Policy[i3].IDSelector,
			To: reference.To{
				List:    &PolicyList{},
				Managed: &Policy{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Policy[i3].ID")
		}
		mg.Spec.InitProvider.Policy[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Policy[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}
