// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PolicyBindingsV2InitParameters struct {

	// uuid>). The attribute policies must contain ONLY policies defined for that account. The prefix urn:dtaccount: MUST be omitted here.
	// The UUID of the account (`urn:dtaccount:<account-uuid>`). The attribute `policies` must contain ONLY policies defined for that account. The prefix `urn:dtaccount:` MUST be omitted here.
	Account *string `json:"account,omitempty" tf:"account,omitempty"`

	// (String) The ID of the environment (https://.live.dynatrace.com). The attribute policies must contain ONLY policies defined for that environment.
	// The ID of the environment (https://<environmentid>.live.dynatrace.com). The attribute `policies` must contain ONLY policies defined for that environment.
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// (String) The UUID of the group to which the policy applies
	// The UUID of the group to which the policy applies
	// +crossplane:generate:reference:type=Group
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// Reference to a Group to populate group.
	// +kubebuilder:validation:Optional
	GroupRef *v2.Reference `json:"groupRef,omitempty" tf:"-"`

	// Selector for a Group to populate group.
	// +kubebuilder:validation:Optional
	GroupSelector *v2.Selector `json:"groupSelector,omitempty" tf:"-"`

	// (Block Set) A list of Policies (ID and parameters/metadata) referring to policies bound to that group. It's not possible to mix policies here that are defined for different scopes (different accounts or environments) than specified via attributes account or environment. (see below for nested schema)
	// A list of Policies (ID and parameters/metadata) referring to policies bound to that group. It's not possible to mix policies here that are defined for different scopes (different accounts or environments) than specified via attributes `account` or `environment`.
	Policy []PolicyBindingsV2PolicyInitParameters `json:"policy,omitempty" tf:"policy,omitempty"`
}

type PolicyBindingsV2Observation struct {

	// uuid>). The attribute policies must contain ONLY policies defined for that account. The prefix urn:dtaccount: MUST be omitted here.
	// The UUID of the account (`urn:dtaccount:<account-uuid>`). The attribute `policies` must contain ONLY policies defined for that account. The prefix `urn:dtaccount:` MUST be omitted here.
	Account *string `json:"account,omitempty" tf:"account,omitempty"`

	// (String) The ID of the environment (https://.live.dynatrace.com). The attribute policies must contain ONLY policies defined for that environment.
	// The ID of the environment (https://<environmentid>.live.dynatrace.com). The attribute `policies` must contain ONLY policies defined for that environment.
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// (String) The UUID of the group to which the policy applies
	// The UUID of the group to which the policy applies
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Block Set) A list of Policies (ID and parameters/metadata) referring to policies bound to that group. It's not possible to mix policies here that are defined for different scopes (different accounts or environments) than specified via attributes account or environment. (see below for nested schema)
	// A list of Policies (ID and parameters/metadata) referring to policies bound to that group. It's not possible to mix policies here that are defined for different scopes (different accounts or environments) than specified via attributes `account` or `environment`.
	Policy []PolicyBindingsV2PolicyObservation `json:"policy,omitempty" tf:"policy,omitempty"`
}

type PolicyBindingsV2Parameters struct {

	// uuid>). The attribute policies must contain ONLY policies defined for that account. The prefix urn:dtaccount: MUST be omitted here.
	// The UUID of the account (`urn:dtaccount:<account-uuid>`). The attribute `policies` must contain ONLY policies defined for that account. The prefix `urn:dtaccount:` MUST be omitted here.
	// +kubebuilder:validation:Optional
	Account *string `json:"account,omitempty" tf:"account,omitempty"`

	// (String) The ID of the environment (https://.live.dynatrace.com). The attribute policies must contain ONLY policies defined for that environment.
	// The ID of the environment (https://<environmentid>.live.dynatrace.com). The attribute `policies` must contain ONLY policies defined for that environment.
	// +kubebuilder:validation:Optional
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// (String) The UUID of the group to which the policy applies
	// The UUID of the group to which the policy applies
	// +crossplane:generate:reference:type=Group
	// +kubebuilder:validation:Optional
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// Reference to a Group to populate group.
	// +kubebuilder:validation:Optional
	GroupRef *v2.Reference `json:"groupRef,omitempty" tf:"-"`

	// Selector for a Group to populate group.
	// +kubebuilder:validation:Optional
	GroupSelector *v2.Selector `json:"groupSelector,omitempty" tf:"-"`

	// (Block Set) A list of Policies (ID and parameters/metadata) referring to policies bound to that group. It's not possible to mix policies here that are defined for different scopes (different accounts or environments) than specified via attributes account or environment. (see below for nested schema)
	// A list of Policies (ID and parameters/metadata) referring to policies bound to that group. It's not possible to mix policies here that are defined for different scopes (different accounts or environments) than specified via attributes `account` or `environment`.
	// +kubebuilder:validation:Optional
	Policy []PolicyBindingsV2PolicyParameters `json:"policy,omitempty" tf:"policy,omitempty"`
}

type PolicyBindingsV2PolicyInitParameters struct {

	// (Set of String)
	// +crossplane:generate:reference:type=PolicyBoundary
	// +listType=set
	Boundaries []*string `json:"boundaries,omitempty" tf:"boundaries,omitempty"`

	// References to PolicyBoundary to populate boundaries.
	// +kubebuilder:validation:Optional
	BoundariesRefs []v2.Reference `json:"boundariesRefs,omitempty" tf:"-"`

	// Selector for a list of PolicyBoundary to populate boundaries.
	// +kubebuilder:validation:Optional
	BoundariesSelector *v2.Selector `json:"boundariesSelector,omitempty" tf:"-"`

	// (String) The ID of this resource.
	// Either the attribute `id` or the attribute `uuid` of a `dynatrace_iam_policy`. Initially just the `id` attribute was supported (which is a concatenation of several configuration settings) - and is still supported for backwards compatibility
	// +crossplane:generate:reference:type=Policy
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a Policy to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v2.Reference `json:"idRef,omitempty" tf:"-"`

	// Selector for a Policy to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v2.Selector `json:"idSelector,omitempty" tf:"-"`

	// (Map of String)
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (Map of String)
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`
}

type PolicyBindingsV2PolicyObservation struct {

	// (Set of String)
	// +listType=set
	Boundaries []*string `json:"boundaries,omitempty" tf:"boundaries,omitempty"`

	// (String) The ID of this resource.
	// Either the attribute `id` or the attribute `uuid` of a `dynatrace_iam_policy`. Initially just the `id` attribute was supported (which is a concatenation of several configuration settings) - and is still supported for backwards compatibility
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String)
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (Map of String)
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`
}

type PolicyBindingsV2PolicyParameters struct {

	// (Set of String)
	// +crossplane:generate:reference:type=PolicyBoundary
	// +kubebuilder:validation:Optional
	// +listType=set
	Boundaries []*string `json:"boundaries,omitempty" tf:"boundaries,omitempty"`

	// References to PolicyBoundary to populate boundaries.
	// +kubebuilder:validation:Optional
	BoundariesRefs []v2.Reference `json:"boundariesRefs,omitempty" tf:"-"`

	// Selector for a list of PolicyBoundary to populate boundaries.
	// +kubebuilder:validation:Optional
	BoundariesSelector *v2.Selector `json:"boundariesSelector,omitempty" tf:"-"`

	// (String) The ID of this resource.
	// Either the attribute `id` or the attribute `uuid` of a `dynatrace_iam_policy`. Initially just the `id` attribute was supported (which is a concatenation of several configuration settings) - and is still supported for backwards compatibility
	// +crossplane:generate:reference:type=Policy
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a Policy to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v2.Reference `json:"idRef,omitempty" tf:"-"`

	// Selector for a Policy to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v2.Selector `json:"idSelector,omitempty" tf:"-"`

	// (Map of String)
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (Map of String)
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`
}

// PolicyBindingsV2Spec defines the desired state of PolicyBindingsV2
type PolicyBindingsV2Spec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   PolicyBindingsV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyBindingsV2InitParameters `json:"initProvider,omitempty"`
}

// PolicyBindingsV2Status defines the observed state of PolicyBindingsV2.
type PolicyBindingsV2Status struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PolicyBindingsV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PolicyBindingsV2 is the Schema for the PolicyBindingsV2s API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type PolicyBindingsV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PolicyBindingsV2Spec   `json:"spec"`
	Status            PolicyBindingsV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyBindingsV2List contains a list of PolicyBindingsV2s
type PolicyBindingsV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyBindingsV2 `json:"items"`
}

// Repository type metadata.
var (
	PolicyBindingsV2_Kind             = "PolicyBindingsV2"
	PolicyBindingsV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyBindingsV2_Kind}.String()
	PolicyBindingsV2_KindAPIVersion   = PolicyBindingsV2_Kind + "." + CRDGroupVersion.String()
	PolicyBindingsV2_GroupVersionKind = CRDGroupVersion.WithKind(PolicyBindingsV2_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyBindingsV2{}, &PolicyBindingsV2List{})
}
