// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ServiceUserInitParameters struct {

	// (String) The description of the service user
	// The description of the service user
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Set of String) The UUIDs of the groups the service user belongs to
	// The UUIDs of the groups the service user belongs to
	// +listType=set
	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// (String) The name of the service user
	// The name of the service user
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ServiceUserObservation struct {

	// (String) The description of the service user
	// The description of the service user
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The email of the service user
	// The email of the service user
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Set of String) The UUIDs of the groups the service user belongs to
	// The UUIDs of the groups the service user belongs to
	// +listType=set
	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the service user
	// The name of the service user
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ServiceUserParameters struct {

	// (String) The description of the service user
	// The description of the service user
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Set of String) The UUIDs of the groups the service user belongs to
	// The UUIDs of the groups the service user belongs to
	// +kubebuilder:validation:Optional
	// +listType=set
	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// (String) The name of the service user
	// The name of the service user
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// ServiceUserSpec defines the desired state of ServiceUser
type ServiceUserSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ServiceUserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServiceUserInitParameters `json:"initProvider,omitempty"`
}

// ServiceUserStatus defines the observed state of ServiceUser.
type ServiceUserStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ServiceUserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServiceUser is the Schema for the ServiceUsers API. The resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,dynatrace}
type ServiceUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ServiceUserSpec   `json:"spec"`
	Status ServiceUserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceUserList contains a list of ServiceUsers
type ServiceUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceUser `json:"items"`
}

// Repository type metadata.
var (
	ServiceUser_Kind             = "ServiceUser"
	ServiceUser_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServiceUser_Kind}.String()
	ServiceUser_KindAPIVersion   = ServiceUser_Kind + "." + CRDGroupVersion.String()
	ServiceUser_GroupVersionKind = CRDGroupVersion.WithKind(ServiceUser_Kind)
)

func init() {
	SchemeBuilder.Register(&ServiceUser{}, &ServiceUserList{})
}
