apiVersion: iam.dynatrace.m.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/group
  labels:
    testing.upbound.io/example-name: Restricted
  name: restricted
  namespace: crossplane-system
spec:
  forProvider:
    name: Restricted
