apiVersion: policy.dynatrace.m.crossplane.io/v1alpha1
kind: Bindings
metadata:
  annotations:
    meta.upbound.io/example-id: policy/v1alpha1/bindings
  labels:
    testing.upbound.io/example-name: env_bindings
  name: env-bindings
  namespace: crossplane-system
spec:
  forProvider:
    environment: '########-####-####-####-############'
    group: ${dynatrace_user_group.my_group.id}
    policies:
    - ${dynatrace_policy.env_policy.id}

---

apiVersion: policy.dynatrace.m.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: policy/v1alpha1/bindings
  labels:
    testing.upbound.io/example-name: cluster_policy
  name: cluster-policy
  namespace: crossplane-system
spec:
  forProvider:
    cluster: '########-####-####-####-############'
    name: my_policy_valid_for_all_environments_in_this_cluster
    statementQuery: ALLOW settings:objects:read, settings:schemas:read WHERE settings:schemaId
      = "string";

---

apiVersion: policy.dynatrace.m.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: policy/v1alpha1/bindings
  labels:
    testing.upbound.io/example-name: env_policy
  name: env-policy
  namespace: crossplane-system
spec:
  forProvider:
    environment: '########-####-####-####-############'
    name: my_policy_valid_for_environment_########-####-####-####-############
    statementQuery: ALLOW settings:objects:read, settings:schemas:read WHERE settings:schemaId
      = "string";

---

apiVersion: user.dynatrace.m.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: policy/v1alpha1/bindings
  labels:
    testing.upbound.io/example-name: my_group
  name: my-group
  namespace: crossplane-system
spec:
  forProvider:
    name: my_group
